import './header'
import './content'
import './footer'

import './main/1preview'
import './main/2info'
import './main/3generator'
import './main/4catalog'
import './main/5reasons'
import './main/6partners'
import './main/7reviews'

import './catalog'
import './feedback'
import './contacts'
