import './header'
import './content'
import './footer'

import './main/1preview'
import './main/2info'
import './main/3generator'
import './main/4catalog'
import './main/5reasons'
import './main/6partners'
import './main/7reviews'

import './about/a1'
import './about/a2'
import './about/a3'
import './about/a5'
import './about/a6'

import './advantages'

import './shipping/a1'
import './shipping/a2'
import './shipping/a3'
import './shipping/a4'
import './shipping/a5'

import './catalog'
import './feedback'
import './contacts'
import './404'
import './reviews'
import './shop'
